@BasicAuthenticationDemo_HostAddress = http://localhost:5082

GET {{BasicAuthenticationDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BasicAuthenticationDemo_HostAddress}}/api/secure/secret-admin
Accept: application/json
Authorization: Basic YWRtaW46cGFzMTIz

###

GET {{BasicAuthenticationDemo_HostAddress}}/api/secure/secret-developer
Accept: application/json
Authorization: Basic YWRtaW46cGFzMTIz

###
GET {{BasicAuthenticationDemo_HostAddress}}/api/secure/public
Accept: application/json

###